global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:3000']
    metrics_path: /metrics

  - job_name: 'cart-service'
    static_configs:
      - targets: ['cart-service:3001']
    metrics_path: /metrics

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: /health
